print(1, "Galin")
print(2, 'Petya')
print(3, 'Ivan Georgiev')
print(4, "Petar")
print(5, "Ivan Ivanov")
print(6, "Maria")
print(7, "Plamena")
print(8, "Atanas")
print(9, "Grigor")
print(10, "Marin")
